### ISSUE TITLE
atropos does not work with python 3.8 because of clock module

### ISSUE THREAD

**Issue by kingralph80** [jdidion/atropos#87]
Dear authors,

when I run atropos I get:
    self.start_time = Timestamp()
  File "/netscratch/dep_psl/grp_frommer/Thomas/bin/miniconda3/envs/atropos/lib/python3.8/site-packages/atropos-1.1.23-py3.8-linux-x86_64.egg/atropos/util/__init__.py", line 227, in __init__
    self.clock = time.clock()
AttributeError: module 'time' has no attribute 'clock'

After checking online i found that the time module has been removed from python 3.8:

From the Python 3.8 doc:

The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

**Comment by jdidion** [comment]
Thanks for reporting this. I should be able to get a new version out shortly with this resolved.

**Comment by jdidion** [comment]
Fixed in 1.1.24
